### ISSUE TITLE
[Setup] - Add initial config

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/union-developers#1]
## Description
Add initial project setup.

## Task
- [x] Add Styled Components
- [x] Add Storybook
- [x] Config Eslint
- [x] Add Prettier
- [x] Add Husky + Lint Staged
- [x] Add Commitlint
- [x] Add Vitest
- [x] Add addon for test acessibility on [Storybook](https://storybook.js.org/docs/react/writing-tests/accessibility-testing)
- [x] Add [Plop ](https://plopjs.com/documentation/#getting-started)
- [x] Add engine config files
- [x] Add CI config
- [x] Add Github issue template
